### ISSUE TITLE
NaNs in diss_spikeship

### ISSUE THREAD

**Issue by guidomeijer** [bsotomayorg/SpikeShip#2]
I'm working on implementing SpikeShip on my data but I often have the issue that after running `diss_spikeship = spikeship.distances(ripple_spike_times, ii_spike_times)` there are NaNs in `diss_spikeship`. I've tried setting various minimum criteria (minimum number of neurons/events/spikes etc) which sometimes works, but not always. Under which conditions does the algorithm output a NaN exactly? Then I can make sure to exclude those.
Cheers!

**Comment by bsotomayorg** [comment]
Hey, Guido! The output is NaN when it's not possible to compare two epochs or trials. Ensure you have neurons that spike in the two epochs you're comparing. Perhaps increasing the window length of your analysis or adjusting the number of neurons might help. Let me know!

**Comment by guidomeijer** [comment]
Thanks I'll try to do this. If it does fail for some trail pairs, is it ok to set only those pairs to 0 in the distance matrix before running TSNE? Excluding both entire trials if one trial pair fails would result in a lot of data loss

**Comment by bsotomayorg** [comment]
In this context, when a distance matrix contains a value of 0, it signifies that those epochs are considered identical. Since you cannot exclude those epochs, an alternative approach could involve inserting the maximum feasible value (e.g., the window length) in those instances instead.

**Comment by guidomeijer** [comment]
That makes total sense, I wasn't thinking. Thanks for all your help!
