### ISSUE TITLE
Some help getting my data in the right format

### ISSUE THREAD

**Issue by guidomeijer** [bsotomayorg/SpikeShip#3]
Hi Boris, 

SpikeShip itself is running smooth and fast but getting my spiking data in the right input format for SpikeShip is currently taking very long and I was wondering if you have conversion functions already. The required input format is very unintuitive to me and I'm losing a lot of time in for loops but I can't easily see how to make it faster. 

My data is in the format used by the IBL (and I believe Allen as well). It consist of an array `1xN spike_times` which contains all the times of N spikes. Then there is a `1xN spike_clusters` array which contains the neuron identity of each spike. Then I have a `Nx2 events` array which contains the start (first column) and stop (second column) times of all my N events.

Do you happen to have a conversion script to go from this data format to the one required by SpikeShip or do you have an idea on how to do this efficiently?

**Comment by bsotomayorg** [comment]
Hi Guido,
I uploaded an example of how to convert data with the format you mentioned.
Please check `SpikeShip/notebooks/example_data_conversion.ipynb` and let me know if you have any questions.

**Comment by guidomeijer** [comment]
Thanks, this is super helpful! However I do think there is a small bug in the code. Instead of
```
temp_ii_spike_times.append([current_count, (count_st+current_count)])
current_count += current_count
```
it should be
```
temp_ii_spike_times.append([count_st, (count_st+current_count)])
count_st += current_count
```
It's also still quite slow. For 45 neurons with 958697 spikes and 312 epochs it takes 21.1 seconds to run. I'll see if I can find ways to speed it up.

**Comment by bsotomayorg** [comment]
That's correct. Thx and great that it helped!

**Comment by guidomeijer** [comment]
I optimized your function and it now runs much faster! Also I never realized the spike times should be relative to the epoch onset. Maybe good to emphasize in the other example notebooks? Thanks again for your help

```
def to_spikeship_dataformat(raw_spike_times, neuron_ids, epoch_intervals):
    """
    Processes spike times relative to epoch intervals and return `spike_times` and
    `ii_spike_times` indices for spikeship's data format. `raw_spike_times` is an
    array with all the spike times of a dataset, `neuron_ids` is the neuron to
    which such spike belongs to, and `epoch_intervals` contains the start and end
    time to consider for defining each epoch.

    Parameters
    ----------
    raw_spike_times : numpy.ndarray
    Array of 1xn which contains all the spike times (n).
    neuron_ids : numpy.ndarray
    Array of 1xN labels which correspond to neurons identity of each spike (i.e., N 
    neurons).
    epoch_intervals : numpy.ndarray
    Array of `Mx2` values. `M` corresponds to the number of trials or epochs.
    First and second columns correspond to start and stop times, respectively.

    Returns
    -------
    spike_times : numpy.ndarray
        Array with relative spike times.
    ii_spikes_times: numpy.ndarray
        `(M,N,2)`-Array with indices per neuron (N) and epoch (M).
    """
    
    M = epoch_intervals.shape[0]

    spike_times = np.empty(0)
    ii_spike_times = np.zeros((epoch_intervals.shape[0],
                               np.max(neuron_ids) + 1, 2)).astype(int)

    # we can save time by excluding spikes outside of the outer epoch boundaries
    neuron_ids = neuron_ids[(raw_spike_times >= np.min(epoch_intervals))
                            & (raw_spike_times <= np.max(epoch_intervals))]
    raw_spike_times = raw_spike_times[(raw_spike_times >= np.min(epoch_intervals))
                                      & (raw_spike_times <= np.max(epoch_intervals))]

    for i_M in range(M):
        t_start = epoch_intervals[i_M][0]
        t_end = epoch_intervals[i_M][1]
        
        temp_spike_train = raw_spike_times[(raw_spike_times >= t_start)
                                           & (raw_spike_times < t_end)]
        # spike times are relative to trial onset
        temp_spike_train = temp_spike_train - t_start
        temp_neurons = neuron_ids[(raw_spike_times >= t_start)
                                  & (raw_spike_times < t_end)]      

        this_order = np.argsort(temp_neurons)
        temp_spike_train = temp_spike_train[this_order]
        temp_neurons = temp_neurons[this_order]
        
        for i_N in np.unique(temp_neurons):
            ii_spike_times[i_M, i_N, :] = (np.array([np.argmax(temp_neurons >= i_N),
                                                    np.sum(temp_neurons <= i_N)])
                                           + spike_times.shape[0])
        spike_times = np.append(spike_times, temp_spike_train)
    
    ii_spike_times = ii_spike_times[:, np.unique(neuron_ids), :]
        
    return spike_times, ii_spike_times
```

**Comment by bsotomayorg** [comment]
Great! Yeah it will run much faster if you remove those spike times that are not included in your epochs, so it was a good idea to implement that. Also using NumPy arrays rather than python lists ;)

Let me know if you have any other questions.
Boris.
